// UART_qsys.v

// Generated using ACDS version 13.0sp1 232 at 2018.03.17.18:02:11

`timescale 1 ps / 1 ps
module UART_qsys (
		input  wire  clk_clk,        //      clk.clk
		input  wire  reset_reset_n,  //    reset.reset_n
		input  wire  uart_io_rxd,    //  uart_io.rxd
		output wire  uart_io_txd,    //         .txd
		output wire  uart_led_led_0, // uart_led.led_0
		output wire  uart_led_led_1  //         .led_1
	);

	wire         master_0_master_waitrequest;                                                          // master_0_master_translator:av_waitrequest -> master_0:master_waitrequest
	wire  [31:0] master_0_master_writedata;                                                            // master_0:master_writedata -> master_0_master_translator:av_writedata
	wire  [31:0] master_0_master_address;                                                              // master_0:master_address -> master_0_master_translator:av_address
	wire         master_0_master_write;                                                                // master_0:master_write -> master_0_master_translator:av_write
	wire         master_0_master_read;                                                                 // master_0:master_read -> master_0_master_translator:av_read
	wire  [31:0] master_0_master_readdata;                                                             // master_0_master_translator:av_readdata -> master_0:master_readdata
	wire   [3:0] master_0_master_byteenable;                                                           // master_0:master_byteenable -> master_0_master_translator:av_byteenable
	wire         master_0_master_readdatavalid;                                                        // master_0_master_translator:av_readdatavalid -> master_0:master_readdatavalid
	wire         uart_ttl_0_avmm_translator_avalon_anti_slave_0_waitrequest;                           // UART_TTL_0:avmm_waitrequest -> UART_TTL_0_avmm_translator:av_waitrequest
	wire  [15:0] uart_ttl_0_avmm_translator_avalon_anti_slave_0_writedata;                             // UART_TTL_0_avmm_translator:av_writedata -> UART_TTL_0:avmm_writedata
	wire   [0:0] uart_ttl_0_avmm_translator_avalon_anti_slave_0_address;                               // UART_TTL_0_avmm_translator:av_address -> UART_TTL_0:avmm_address
	wire         uart_ttl_0_avmm_translator_avalon_anti_slave_0_write;                                 // UART_TTL_0_avmm_translator:av_write -> UART_TTL_0:avmm_write
	wire         uart_ttl_0_avmm_translator_avalon_anti_slave_0_read;                                  // UART_TTL_0_avmm_translator:av_read -> UART_TTL_0:avmm_read
	wire  [15:0] uart_ttl_0_avmm_translator_avalon_anti_slave_0_readdata;                              // UART_TTL_0:avmm_readdata -> UART_TTL_0_avmm_translator:av_readdata
	wire         master_0_master_translator_avalon_universal_master_0_waitrequest;                     // master_0_master_translator_avalon_universal_master_0_agent:av_waitrequest -> master_0_master_translator:uav_waitrequest
	wire   [2:0] master_0_master_translator_avalon_universal_master_0_burstcount;                      // master_0_master_translator:uav_burstcount -> master_0_master_translator_avalon_universal_master_0_agent:av_burstcount
	wire  [31:0] master_0_master_translator_avalon_universal_master_0_writedata;                       // master_0_master_translator:uav_writedata -> master_0_master_translator_avalon_universal_master_0_agent:av_writedata
	wire  [31:0] master_0_master_translator_avalon_universal_master_0_address;                         // master_0_master_translator:uav_address -> master_0_master_translator_avalon_universal_master_0_agent:av_address
	wire         master_0_master_translator_avalon_universal_master_0_lock;                            // master_0_master_translator:uav_lock -> master_0_master_translator_avalon_universal_master_0_agent:av_lock
	wire         master_0_master_translator_avalon_universal_master_0_write;                           // master_0_master_translator:uav_write -> master_0_master_translator_avalon_universal_master_0_agent:av_write
	wire         master_0_master_translator_avalon_universal_master_0_read;                            // master_0_master_translator:uav_read -> master_0_master_translator_avalon_universal_master_0_agent:av_read
	wire  [31:0] master_0_master_translator_avalon_universal_master_0_readdata;                        // master_0_master_translator_avalon_universal_master_0_agent:av_readdata -> master_0_master_translator:uav_readdata
	wire         master_0_master_translator_avalon_universal_master_0_debugaccess;                     // master_0_master_translator:uav_debugaccess -> master_0_master_translator_avalon_universal_master_0_agent:av_debugaccess
	wire   [3:0] master_0_master_translator_avalon_universal_master_0_byteenable;                      // master_0_master_translator:uav_byteenable -> master_0_master_translator_avalon_universal_master_0_agent:av_byteenable
	wire         master_0_master_translator_avalon_universal_master_0_readdatavalid;                   // master_0_master_translator_avalon_universal_master_0_agent:av_readdatavalid -> master_0_master_translator:uav_readdatavalid
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_waitrequest;             // UART_TTL_0_avmm_translator:uav_waitrequest -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:m0_waitrequest
	wire   [1:0] uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_burstcount;              // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:m0_burstcount -> UART_TTL_0_avmm_translator:uav_burstcount
	wire  [15:0] uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_writedata;               // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:m0_writedata -> UART_TTL_0_avmm_translator:uav_writedata
	wire  [31:0] uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_address;                 // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:m0_address -> UART_TTL_0_avmm_translator:uav_address
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_write;                   // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:m0_write -> UART_TTL_0_avmm_translator:uav_write
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_lock;                    // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:m0_lock -> UART_TTL_0_avmm_translator:uav_lock
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_read;                    // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:m0_read -> UART_TTL_0_avmm_translator:uav_read
	wire  [15:0] uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_readdata;                // UART_TTL_0_avmm_translator:uav_readdata -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:m0_readdata
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_readdatavalid;           // UART_TTL_0_avmm_translator:uav_readdatavalid -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:m0_readdatavalid
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_debugaccess;             // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:m0_debugaccess -> UART_TTL_0_avmm_translator:uav_debugaccess
	wire   [1:0] uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_byteenable;              // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:m0_byteenable -> UART_TTL_0_avmm_translator:uav_byteenable
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_endofpacket;      // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rf_source_endofpacket -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo:in_endofpacket
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_valid;            // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rf_source_valid -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo:in_valid
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_startofpacket;    // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rf_source_startofpacket -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo:in_startofpacket
	wire  [81:0] uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_data;             // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rf_source_data -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo:in_data
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_ready;            // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo:in_ready -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rf_source_ready
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket;   // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo:out_endofpacket -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rf_sink_endofpacket
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid;         // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo:out_valid -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rf_sink_valid
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket; // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo:out_startofpacket -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rf_sink_startofpacket
	wire  [81:0] uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data;          // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo:out_data -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rf_sink_data
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready;         // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rf_sink_ready -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo:out_ready
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid;       // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rdata_fifo_src_valid -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_valid
	wire  [17:0] uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data;        // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rdata_fifo_src_data -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_data
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready;       // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rdata_fifo_sink_ready -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rdata_fifo_src_ready
	wire         master_0_master_translator_avalon_universal_master_0_agent_cp_endofpacket;            // master_0_master_translator_avalon_universal_master_0_agent:cp_endofpacket -> addr_router:sink_endofpacket
	wire         master_0_master_translator_avalon_universal_master_0_agent_cp_valid;                  // master_0_master_translator_avalon_universal_master_0_agent:cp_valid -> addr_router:sink_valid
	wire         master_0_master_translator_avalon_universal_master_0_agent_cp_startofpacket;          // master_0_master_translator_avalon_universal_master_0_agent:cp_startofpacket -> addr_router:sink_startofpacket
	wire  [98:0] master_0_master_translator_avalon_universal_master_0_agent_cp_data;                   // master_0_master_translator_avalon_universal_master_0_agent:cp_data -> addr_router:sink_data
	wire         master_0_master_translator_avalon_universal_master_0_agent_cp_ready;                  // addr_router:sink_ready -> master_0_master_translator_avalon_universal_master_0_agent:cp_ready
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_endofpacket;             // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rp_endofpacket -> id_router:sink_endofpacket
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_valid;                   // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rp_valid -> id_router:sink_valid
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_startofpacket;           // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rp_startofpacket -> id_router:sink_startofpacket
	wire  [80:0] uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_data;                    // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rp_data -> id_router:sink_data
	wire         uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_ready;                   // id_router:sink_ready -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:rp_ready
	wire         burst_adapter_source0_endofpacket;                                                    // burst_adapter:source0_endofpacket -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:cp_endofpacket
	wire         burst_adapter_source0_valid;                                                          // burst_adapter:source0_valid -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:cp_valid
	wire         burst_adapter_source0_startofpacket;                                                  // burst_adapter:source0_startofpacket -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:cp_startofpacket
	wire  [80:0] burst_adapter_source0_data;                                                           // burst_adapter:source0_data -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:cp_data
	wire         burst_adapter_source0_ready;                                                          // UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:cp_ready -> burst_adapter:source0_ready
	wire   [0:0] burst_adapter_source0_channel;                                                        // burst_adapter:source0_channel -> UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:cp_channel
	wire         rst_controller_reset_out_reset;                                                       // rst_controller:reset_out -> [UART_TTL_0:rstn, UART_TTL_0_avmm_translator:reset, UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent:reset, UART_TTL_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo:reset, addr_router:reset, burst_adapter:reset, cmd_xbar_demux:reset, id_router:reset, master_0_master_translator:reset, master_0_master_translator_avalon_universal_master_0_agent:reset, rsp_xbar_demux:reset, width_adapter:reset, width_adapter_001:reset]
	wire         cmd_xbar_demux_src0_endofpacket;                                                      // cmd_xbar_demux:src0_endofpacket -> width_adapter:in_endofpacket
	wire         cmd_xbar_demux_src0_valid;                                                            // cmd_xbar_demux:src0_valid -> width_adapter:in_valid
	wire         cmd_xbar_demux_src0_startofpacket;                                                    // cmd_xbar_demux:src0_startofpacket -> width_adapter:in_startofpacket
	wire  [98:0] cmd_xbar_demux_src0_data;                                                             // cmd_xbar_demux:src0_data -> width_adapter:in_data
	wire   [0:0] cmd_xbar_demux_src0_channel;                                                          // cmd_xbar_demux:src0_channel -> width_adapter:in_channel
	wire         rsp_xbar_demux_src0_endofpacket;                                                      // rsp_xbar_demux:src0_endofpacket -> master_0_master_translator_avalon_universal_master_0_agent:rp_endofpacket
	wire         rsp_xbar_demux_src0_valid;                                                            // rsp_xbar_demux:src0_valid -> master_0_master_translator_avalon_universal_master_0_agent:rp_valid
	wire         rsp_xbar_demux_src0_startofpacket;                                                    // rsp_xbar_demux:src0_startofpacket -> master_0_master_translator_avalon_universal_master_0_agent:rp_startofpacket
	wire  [98:0] rsp_xbar_demux_src0_data;                                                             // rsp_xbar_demux:src0_data -> master_0_master_translator_avalon_universal_master_0_agent:rp_data
	wire   [0:0] rsp_xbar_demux_src0_channel;                                                          // rsp_xbar_demux:src0_channel -> master_0_master_translator_avalon_universal_master_0_agent:rp_channel
	wire         addr_router_src_endofpacket;                                                          // addr_router:src_endofpacket -> cmd_xbar_demux:sink_endofpacket
	wire         addr_router_src_valid;                                                                // addr_router:src_valid -> cmd_xbar_demux:sink_valid
	wire         addr_router_src_startofpacket;                                                        // addr_router:src_startofpacket -> cmd_xbar_demux:sink_startofpacket
	wire  [98:0] addr_router_src_data;                                                                 // addr_router:src_data -> cmd_xbar_demux:sink_data
	wire   [0:0] addr_router_src_channel;                                                              // addr_router:src_channel -> cmd_xbar_demux:sink_channel
	wire         addr_router_src_ready;                                                                // cmd_xbar_demux:sink_ready -> addr_router:src_ready
	wire         rsp_xbar_demux_src0_ready;                                                            // master_0_master_translator_avalon_universal_master_0_agent:rp_ready -> rsp_xbar_demux:src0_ready
	wire         cmd_xbar_demux_src0_ready;                                                            // width_adapter:in_ready -> cmd_xbar_demux:src0_ready
	wire         width_adapter_src_endofpacket;                                                        // width_adapter:out_endofpacket -> burst_adapter:sink0_endofpacket
	wire         width_adapter_src_valid;                                                              // width_adapter:out_valid -> burst_adapter:sink0_valid
	wire         width_adapter_src_startofpacket;                                                      // width_adapter:out_startofpacket -> burst_adapter:sink0_startofpacket
	wire  [80:0] width_adapter_src_data;                                                               // width_adapter:out_data -> burst_adapter:sink0_data
	wire         width_adapter_src_ready;                                                              // burst_adapter:sink0_ready -> width_adapter:out_ready
	wire   [0:0] width_adapter_src_channel;                                                            // width_adapter:out_channel -> burst_adapter:sink0_channel
	wire         id_router_src_endofpacket;                                                            // id_router:src_endofpacket -> width_adapter_001:in_endofpacket
	wire         id_router_src_valid;                                                                  // id_router:src_valid -> width_adapter_001:in_valid
	wire         id_router_src_startofpacket;                                                          // id_router:src_startofpacket -> width_adapter_001:in_startofpacket
	wire  [80:0] id_router_src_data;                                                                   // id_router:src_data -> width_adapter_001:in_data
	wire   [0:0] id_router_src_channel;                                                                // id_router:src_channel -> width_adapter_001:in_channel
	wire         id_router_src_ready;                                                                  // width_adapter_001:in_ready -> id_router:src_ready
	wire         width_adapter_001_src_endofpacket;                                                    // width_adapter_001:out_endofpacket -> rsp_xbar_demux:sink_endofpacket
	wire         width_adapter_001_src_valid;                                                          // width_adapter_001:out_valid -> rsp_xbar_demux:sink_valid
	wire         width_adapter_001_src_startofpacket;                                                  // width_adapter_001:out_startofpacket -> rsp_xbar_demux:sink_startofpacket
	wire  [98:0] width_adapter_001_src_data;                                                           // width_adapter_001:out_data -> rsp_xbar_demux:sink_data
	wire         width_adapter_001_src_ready;                                                          // rsp_xbar_demux:sink_ready -> width_adapter_001:out_ready
	wire   [0:0] width_adapter_001_src_channel;                                                        // width_adapter_001:out_channel -> rsp_xbar_demux:sink_channel

	UART_qsys_master_0 #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) master_0 (
		.clk_clk              (clk_clk),                       //          clk.clk
		.clk_reset_reset      (~reset_reset_n),                //    clk_reset.reset
		.master_address       (master_0_master_address),       //       master.address
		.master_readdata      (master_0_master_readdata),      //             .readdata
		.master_read          (master_0_master_read),          //             .read
		.master_write         (master_0_master_write),         //             .write
		.master_writedata     (master_0_master_writedata),     //             .writedata
		.master_waitrequest   (master_0_master_waitrequest),   //             .waitrequest
		.master_readdatavalid (master_0_master_readdatavalid), //             .readdatavalid
		.master_byteenable    (master_0_master_byteenable),    //             .byteenable
		.master_reset_reset   ()                               // master_reset.reset
	);

	UART_module #(
		.baudrate (115200),
		.dataBits (8),
		.stopBits (1)
	) uart_ttl_0 (
		.clk              (clk_clk),                                                    //    clock.clk
		.avmm_address     (uart_ttl_0_avmm_translator_avalon_anti_slave_0_address),     //     avmm.address
		.avmm_read        (uart_ttl_0_avmm_translator_avalon_anti_slave_0_read),        //         .read
		.avmm_readdata    (uart_ttl_0_avmm_translator_avalon_anti_slave_0_readdata),    //         .readdata
		.avmm_write       (uart_ttl_0_avmm_translator_avalon_anti_slave_0_write),       //         .write
		.avmm_writedata   (uart_ttl_0_avmm_translator_avalon_anti_slave_0_writedata),   //         .writedata
		.avmm_waitrequest (uart_ttl_0_avmm_translator_avalon_anti_slave_0_waitrequest), //         .waitrequest
		.rstn             (~rst_controller_reset_out_reset),                            //    reset.reset_n
		.rxd              (uart_io_rxd),                                                //  uart_io.rxd
		.txd              (uart_io_txd),                                                //         .txd
		.dataavailable_n  (uart_led_led_0),                                             // uart_led.led_0
		.readyfordata_n   (uart_led_led_1)                                              //         .led_1
	);

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) master_0_master_translator (
		.clk                      (clk_clk),                                                            //                       clk.clk
		.reset                    (rst_controller_reset_out_reset),                                     //                     reset.reset
		.uav_address              (master_0_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount           (master_0_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read                 (master_0_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write                (master_0_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest          (master_0_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid        (master_0_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable           (master_0_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata             (master_0_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata            (master_0_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock                 (master_0_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess          (master_0_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address               (master_0_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest           (master_0_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable            (master_0_master_byteenable),                                         //                          .byteenable
		.av_read                  (master_0_master_read),                                               //                          .read
		.av_readdata              (master_0_master_readdata),                                           //                          .readdata
		.av_readdatavalid         (master_0_master_readdatavalid),                                      //                          .readdatavalid
		.av_write                 (master_0_master_write),                                              //                          .write
		.av_writedata             (master_0_master_writedata),                                          //                          .writedata
		.av_burstcount            (1'b1),                                                               //               (terminated)
		.av_beginbursttransfer    (1'b0),                                                               //               (terminated)
		.av_begintransfer         (1'b0),                                                               //               (terminated)
		.av_chipselect            (1'b0),                                                               //               (terminated)
		.av_lock                  (1'b0),                                                               //               (terminated)
		.av_debugaccess           (1'b0),                                                               //               (terminated)
		.uav_clken                (),                                                                   //               (terminated)
		.av_clken                 (1'b1),                                                               //               (terminated)
		.uav_response             (2'b00),                                                              //               (terminated)
		.av_response              (),                                                                   //               (terminated)
		.uav_writeresponserequest (),                                                                   //               (terminated)
		.uav_writeresponsevalid   (1'b0),                                                               //               (terminated)
		.av_writeresponserequest  (1'b0),                                                               //               (terminated)
		.av_writeresponsevalid    ()                                                                    //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (16),
		.UAV_DATA_W                     (16),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (2),
		.UAV_BYTEENABLE_W               (2),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (2),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (2),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) uart_ttl_0_avmm_translator (
		.clk                      (clk_clk),                                                                    //                      clk.clk
		.reset                    (rst_controller_reset_out_reset),                                             //                    reset.reset
		.uav_address              (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_address),       // avalon_universal_slave_0.address
		.uav_burstcount           (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_burstcount),    //                         .burstcount
		.uav_read                 (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_read),          //                         .read
		.uav_write                (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_write),         //                         .write
		.uav_waitrequest          (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid        (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_readdatavalid), //                         .readdatavalid
		.uav_byteenable           (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_byteenable),    //                         .byteenable
		.uav_readdata             (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_readdata),      //                         .readdata
		.uav_writedata            (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_writedata),     //                         .writedata
		.uav_lock                 (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_lock),          //                         .lock
		.uav_debugaccess          (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_debugaccess),   //                         .debugaccess
		.av_address               (uart_ttl_0_avmm_translator_avalon_anti_slave_0_address),                     //      avalon_anti_slave_0.address
		.av_write                 (uart_ttl_0_avmm_translator_avalon_anti_slave_0_write),                       //                         .write
		.av_read                  (uart_ttl_0_avmm_translator_avalon_anti_slave_0_read),                        //                         .read
		.av_readdata              (uart_ttl_0_avmm_translator_avalon_anti_slave_0_readdata),                    //                         .readdata
		.av_writedata             (uart_ttl_0_avmm_translator_avalon_anti_slave_0_writedata),                   //                         .writedata
		.av_waitrequest           (uart_ttl_0_avmm_translator_avalon_anti_slave_0_waitrequest),                 //                         .waitrequest
		.av_begintransfer         (),                                                                           //              (terminated)
		.av_beginbursttransfer    (),                                                                           //              (terminated)
		.av_burstcount            (),                                                                           //              (terminated)
		.av_byteenable            (),                                                                           //              (terminated)
		.av_readdatavalid         (1'b0),                                                                       //              (terminated)
		.av_writebyteenable       (),                                                                           //              (terminated)
		.av_lock                  (),                                                                           //              (terminated)
		.av_chipselect            (),                                                                           //              (terminated)
		.av_clken                 (),                                                                           //              (terminated)
		.uav_clken                (1'b0),                                                                       //              (terminated)
		.av_debugaccess           (),                                                                           //              (terminated)
		.av_outputenable          (),                                                                           //              (terminated)
		.uav_response             (),                                                                           //              (terminated)
		.av_response              (2'b00),                                                                      //              (terminated)
		.uav_writeresponserequest (1'b0),                                                                       //              (terminated)
		.uav_writeresponsevalid   (),                                                                           //              (terminated)
		.av_writeresponserequest  (),                                                                           //              (terminated)
		.av_writeresponsevalid    (1'b0)                                                                        //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_PROTECTION_H          (92),
		.PKT_PROTECTION_L          (90),
		.PKT_BEGIN_BURST           (85),
		.PKT_BURSTWRAP_H           (77),
		.PKT_BURSTWRAP_L           (77),
		.PKT_BURST_SIZE_H          (80),
		.PKT_BURST_SIZE_L          (78),
		.PKT_BURST_TYPE_H          (82),
		.PKT_BURST_TYPE_L          (81),
		.PKT_BYTE_CNT_H            (76),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_TRANS_LOCK            (72),
		.PKT_TRANS_EXCLUSIVE       (73),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (87),
		.PKT_SRC_ID_L              (87),
		.PKT_DEST_ID_H             (88),
		.PKT_DEST_ID_L             (88),
		.PKT_THREAD_ID_H           (89),
		.PKT_THREAD_ID_L           (89),
		.PKT_CACHE_H               (96),
		.PKT_CACHE_L               (93),
		.PKT_DATA_SIDEBAND_H       (84),
		.PKT_DATA_SIDEBAND_L       (84),
		.PKT_QOS_H                 (86),
		.PKT_QOS_L                 (86),
		.PKT_ADDR_SIDEBAND_H       (83),
		.PKT_ADDR_SIDEBAND_L       (83),
		.PKT_RESPONSE_STATUS_H     (98),
		.PKT_RESPONSE_STATUS_L     (97),
		.ST_DATA_W                 (99),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) master_0_master_translator_avalon_universal_master_0_agent (
		.clk                     (clk_clk),                                                                     //       clk.clk
		.reset                   (rst_controller_reset_out_reset),                                              // clk_reset.reset
		.av_address              (master_0_master_translator_avalon_universal_master_0_address),                //        av.address
		.av_write                (master_0_master_translator_avalon_universal_master_0_write),                  //          .write
		.av_read                 (master_0_master_translator_avalon_universal_master_0_read),                   //          .read
		.av_writedata            (master_0_master_translator_avalon_universal_master_0_writedata),              //          .writedata
		.av_readdata             (master_0_master_translator_avalon_universal_master_0_readdata),               //          .readdata
		.av_waitrequest          (master_0_master_translator_avalon_universal_master_0_waitrequest),            //          .waitrequest
		.av_readdatavalid        (master_0_master_translator_avalon_universal_master_0_readdatavalid),          //          .readdatavalid
		.av_byteenable           (master_0_master_translator_avalon_universal_master_0_byteenable),             //          .byteenable
		.av_burstcount           (master_0_master_translator_avalon_universal_master_0_burstcount),             //          .burstcount
		.av_debugaccess          (master_0_master_translator_avalon_universal_master_0_debugaccess),            //          .debugaccess
		.av_lock                 (master_0_master_translator_avalon_universal_master_0_lock),                   //          .lock
		.cp_valid                (master_0_master_translator_avalon_universal_master_0_agent_cp_valid),         //        cp.valid
		.cp_data                 (master_0_master_translator_avalon_universal_master_0_agent_cp_data),          //          .data
		.cp_startofpacket        (master_0_master_translator_avalon_universal_master_0_agent_cp_startofpacket), //          .startofpacket
		.cp_endofpacket          (master_0_master_translator_avalon_universal_master_0_agent_cp_endofpacket),   //          .endofpacket
		.cp_ready                (master_0_master_translator_avalon_universal_master_0_agent_cp_ready),         //          .ready
		.rp_valid                (rsp_xbar_demux_src0_valid),                                                   //        rp.valid
		.rp_data                 (rsp_xbar_demux_src0_data),                                                    //          .data
		.rp_channel              (rsp_xbar_demux_src0_channel),                                                 //          .channel
		.rp_startofpacket        (rsp_xbar_demux_src0_startofpacket),                                           //          .startofpacket
		.rp_endofpacket          (rsp_xbar_demux_src0_endofpacket),                                             //          .endofpacket
		.rp_ready                (rsp_xbar_demux_src0_ready),                                                   //          .ready
		.av_response             (),                                                                            // (terminated)
		.av_writeresponserequest (1'b0),                                                                        // (terminated)
		.av_writeresponsevalid   ()                                                                             // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_DATA_H                (15),
		.PKT_DATA_L                (0),
		.PKT_BEGIN_BURST           (67),
		.PKT_SYMBOL_W              (8),
		.PKT_BYTEEN_H              (17),
		.PKT_BYTEEN_L              (16),
		.PKT_ADDR_H                (49),
		.PKT_ADDR_L                (18),
		.PKT_TRANS_COMPRESSED_READ (50),
		.PKT_TRANS_POSTED          (51),
		.PKT_TRANS_WRITE           (52),
		.PKT_TRANS_READ            (53),
		.PKT_TRANS_LOCK            (54),
		.PKT_SRC_ID_H              (69),
		.PKT_SRC_ID_L              (69),
		.PKT_DEST_ID_H             (70),
		.PKT_DEST_ID_L             (70),
		.PKT_BURSTWRAP_H           (59),
		.PKT_BURSTWRAP_L           (59),
		.PKT_BYTE_CNT_H            (58),
		.PKT_BYTE_CNT_L            (56),
		.PKT_PROTECTION_H          (74),
		.PKT_PROTECTION_L          (72),
		.PKT_RESPONSE_STATUS_H     (80),
		.PKT_RESPONSE_STATUS_L     (79),
		.PKT_BURST_SIZE_H          (62),
		.PKT_BURST_SIZE_L          (60),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (81),
		.AVS_BURSTCOUNT_W          (2),
		.SUPPRESS_0_BYTEEN_CMD     (1),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent (
		.clk                     (clk_clk),                                                                              //             clk.clk
		.reset                   (rst_controller_reset_out_reset),                                                       //       clk_reset.reset
		.m0_address              (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_address),                 //              m0.address
		.m0_burstcount           (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_lock),                    //                .lock
		.m0_readdata             (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_read),                    //                .read
		.m0_waitrequest          (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_writedata),               //                .writedata
		.m0_write                (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_m0_write),                   //                .write
		.rp_endofpacket          (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_ready),                   //                .ready
		.rp_valid                (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_valid),                   //                .valid
		.rp_data                 (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_data),                    //                .data
		.rp_startofpacket        (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (burst_adapter_source0_ready),                                                          //              cp.ready
		.cp_valid                (burst_adapter_source0_valid),                                                          //                .valid
		.cp_data                 (burst_adapter_source0_data),                                                           //                .data
		.cp_startofpacket        (burst_adapter_source0_startofpacket),                                                  //                .startofpacket
		.cp_endofpacket          (burst_adapter_source0_endofpacket),                                                    //                .endofpacket
		.cp_channel              (burst_adapter_source0_channel),                                                        //                .channel
		.rf_sink_ready           (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready),       // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_sink_data    (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data),        //                .data
		.rdata_fifo_src_ready    (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rdata_fifo_src_data),        //                .data
		.m0_response             (2'b00),                                                                                //     (terminated)
		.m0_writeresponserequest (),                                                                                     //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                                                  //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (82),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo (
		.clk               (clk_clk),                                                                              //       clk.clk
		.reset             (rst_controller_reset_out_reset),                                                       // clk_reset.reset
		.in_data           (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_data),             //        in.data
		.in_valid          (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_valid),            //          .valid
		.in_ready          (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                                                                // (terminated)
		.csr_read          (1'b0),                                                                                 // (terminated)
		.csr_write         (1'b0),                                                                                 // (terminated)
		.csr_readdata      (),                                                                                     // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                                                 // (terminated)
		.almost_full_data  (),                                                                                     // (terminated)
		.almost_empty_data (),                                                                                     // (terminated)
		.in_empty          (1'b0),                                                                                 // (terminated)
		.out_empty         (),                                                                                     // (terminated)
		.in_error          (1'b0),                                                                                 // (terminated)
		.out_error         (),                                                                                     // (terminated)
		.in_channel        (1'b0),                                                                                 // (terminated)
		.out_channel       ()                                                                                      // (terminated)
	);

	UART_qsys_addr_router addr_router (
		.sink_ready         (master_0_master_translator_avalon_universal_master_0_agent_cp_ready),         //      sink.ready
		.sink_valid         (master_0_master_translator_avalon_universal_master_0_agent_cp_valid),         //          .valid
		.sink_data          (master_0_master_translator_avalon_universal_master_0_agent_cp_data),          //          .data
		.sink_startofpacket (master_0_master_translator_avalon_universal_master_0_agent_cp_startofpacket), //          .startofpacket
		.sink_endofpacket   (master_0_master_translator_avalon_universal_master_0_agent_cp_endofpacket),   //          .endofpacket
		.clk                (clk_clk),                                                                     //       clk.clk
		.reset              (rst_controller_reset_out_reset),                                              // clk_reset.reset
		.src_ready          (addr_router_src_ready),                                                       //       src.ready
		.src_valid          (addr_router_src_valid),                                                       //          .valid
		.src_data           (addr_router_src_data),                                                        //          .data
		.src_channel        (addr_router_src_channel),                                                     //          .channel
		.src_startofpacket  (addr_router_src_startofpacket),                                               //          .startofpacket
		.src_endofpacket    (addr_router_src_endofpacket)                                                  //          .endofpacket
	);

	UART_qsys_id_router id_router (
		.sink_ready         (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_ready),         //      sink.ready
		.sink_valid         (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_valid),         //          .valid
		.sink_data          (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_data),          //          .data
		.sink_startofpacket (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_startofpacket), //          .startofpacket
		.sink_endofpacket   (uart_ttl_0_avmm_translator_avalon_universal_slave_0_agent_rp_endofpacket),   //          .endofpacket
		.clk                (clk_clk),                                                                    //       clk.clk
		.reset              (rst_controller_reset_out_reset),                                             // clk_reset.reset
		.src_ready          (id_router_src_ready),                                                        //       src.ready
		.src_valid          (id_router_src_valid),                                                        //          .valid
		.src_data           (id_router_src_data),                                                         //          .data
		.src_channel        (id_router_src_channel),                                                      //          .channel
		.src_startofpacket  (id_router_src_startofpacket),                                                //          .startofpacket
		.src_endofpacket    (id_router_src_endofpacket)                                                   //          .endofpacket
	);

	altera_merlin_burst_adapter #(
		.PKT_ADDR_H                (49),
		.PKT_ADDR_L                (18),
		.PKT_BEGIN_BURST           (67),
		.PKT_BYTE_CNT_H            (58),
		.PKT_BYTE_CNT_L            (56),
		.PKT_BYTEEN_H              (17),
		.PKT_BYTEEN_L              (16),
		.PKT_BURST_SIZE_H          (62),
		.PKT_BURST_SIZE_L          (60),
		.PKT_BURST_TYPE_H          (64),
		.PKT_BURST_TYPE_L          (63),
		.PKT_BURSTWRAP_H           (59),
		.PKT_BURSTWRAP_L           (59),
		.PKT_TRANS_COMPRESSED_READ (50),
		.PKT_TRANS_WRITE           (52),
		.PKT_TRANS_READ            (53),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (81),
		.ST_CHANNEL_W              (1),
		.OUT_BYTE_CNT_H            (57),
		.OUT_BURSTWRAP_H           (59),
		.COMPRESSED_READ_SUPPORT   (0),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1)
	) burst_adapter (
		.clk                   (clk_clk),                             //       cr0.clk
		.reset                 (rst_controller_reset_out_reset),      // cr0_reset.reset
		.sink0_valid           (width_adapter_src_valid),             //     sink0.valid
		.sink0_data            (width_adapter_src_data),              //          .data
		.sink0_channel         (width_adapter_src_channel),           //          .channel
		.sink0_startofpacket   (width_adapter_src_startofpacket),     //          .startofpacket
		.sink0_endofpacket     (width_adapter_src_endofpacket),       //          .endofpacket
		.sink0_ready           (width_adapter_src_ready),             //          .ready
		.source0_valid         (burst_adapter_source0_valid),         //   source0.valid
		.source0_data          (burst_adapter_source0_data),          //          .data
		.source0_channel       (burst_adapter_source0_channel),       //          .channel
		.source0_startofpacket (burst_adapter_source0_startofpacket), //          .startofpacket
		.source0_endofpacket   (burst_adapter_source0_endofpacket),   //          .endofpacket
		.source0_ready         (burst_adapter_source0_ready)          //          .ready
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS        (1),
		.OUTPUT_RESET_SYNC_EDGES ("deassert"),
		.SYNC_DEPTH              (2),
		.RESET_REQUEST_PRESENT   (0)
	) rst_controller (
		.reset_in0  (~reset_reset_n),                 // reset_in0.reset
		.clk        (clk_clk),                        //       clk.clk
		.reset_out  (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req  (),                               // (terminated)
		.reset_in1  (1'b0),                           // (terminated)
		.reset_in2  (1'b0),                           // (terminated)
		.reset_in3  (1'b0),                           // (terminated)
		.reset_in4  (1'b0),                           // (terminated)
		.reset_in5  (1'b0),                           // (terminated)
		.reset_in6  (1'b0),                           // (terminated)
		.reset_in7  (1'b0),                           // (terminated)
		.reset_in8  (1'b0),                           // (terminated)
		.reset_in9  (1'b0),                           // (terminated)
		.reset_in10 (1'b0),                           // (terminated)
		.reset_in11 (1'b0),                           // (terminated)
		.reset_in12 (1'b0),                           // (terminated)
		.reset_in13 (1'b0),                           // (terminated)
		.reset_in14 (1'b0),                           // (terminated)
		.reset_in15 (1'b0)                            // (terminated)
	);

	UART_qsys_cmd_xbar_demux cmd_xbar_demux (
		.clk                (clk_clk),                           //       clk.clk
		.reset              (rst_controller_reset_out_reset),    // clk_reset.reset
		.sink_ready         (addr_router_src_ready),             //      sink.ready
		.sink_channel       (addr_router_src_channel),           //          .channel
		.sink_data          (addr_router_src_data),              //          .data
		.sink_startofpacket (addr_router_src_startofpacket),     //          .startofpacket
		.sink_endofpacket   (addr_router_src_endofpacket),       //          .endofpacket
		.sink_valid         (addr_router_src_valid),             //          .valid
		.src0_ready         (cmd_xbar_demux_src0_ready),         //      src0.ready
		.src0_valid         (cmd_xbar_demux_src0_valid),         //          .valid
		.src0_data          (cmd_xbar_demux_src0_data),          //          .data
		.src0_channel       (cmd_xbar_demux_src0_channel),       //          .channel
		.src0_startofpacket (cmd_xbar_demux_src0_startofpacket), //          .startofpacket
		.src0_endofpacket   (cmd_xbar_demux_src0_endofpacket)    //          .endofpacket
	);

	UART_qsys_cmd_xbar_demux rsp_xbar_demux (
		.clk                (clk_clk),                             //       clk.clk
		.reset              (rst_controller_reset_out_reset),      // clk_reset.reset
		.sink_ready         (width_adapter_001_src_ready),         //      sink.ready
		.sink_channel       (width_adapter_001_src_channel),       //          .channel
		.sink_data          (width_adapter_001_src_data),          //          .data
		.sink_startofpacket (width_adapter_001_src_startofpacket), //          .startofpacket
		.sink_endofpacket   (width_adapter_001_src_endofpacket),   //          .endofpacket
		.sink_valid         (width_adapter_001_src_valid),         //          .valid
		.src0_ready         (rsp_xbar_demux_src0_ready),           //      src0.ready
		.src0_valid         (rsp_xbar_demux_src0_valid),           //          .valid
		.src0_data          (rsp_xbar_demux_src0_data),            //          .data
		.src0_channel       (rsp_xbar_demux_src0_channel),         //          .channel
		.src0_startofpacket (rsp_xbar_demux_src0_startofpacket),   //          .startofpacket
		.src0_endofpacket   (rsp_xbar_demux_src0_endofpacket)      //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (67),
		.IN_PKT_ADDR_L                 (36),
		.IN_PKT_DATA_H                 (31),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (35),
		.IN_PKT_BYTEEN_L               (32),
		.IN_PKT_BYTE_CNT_H             (76),
		.IN_PKT_BYTE_CNT_L             (74),
		.IN_PKT_TRANS_COMPRESSED_READ  (68),
		.IN_PKT_BURSTWRAP_H            (77),
		.IN_PKT_BURSTWRAP_L            (77),
		.IN_PKT_BURST_SIZE_H           (80),
		.IN_PKT_BURST_SIZE_L           (78),
		.IN_PKT_RESPONSE_STATUS_H      (98),
		.IN_PKT_RESPONSE_STATUS_L      (97),
		.IN_PKT_TRANS_EXCLUSIVE        (73),
		.IN_PKT_BURST_TYPE_H           (82),
		.IN_PKT_BURST_TYPE_L           (81),
		.IN_ST_DATA_W                  (99),
		.OUT_PKT_ADDR_H                (49),
		.OUT_PKT_ADDR_L                (18),
		.OUT_PKT_DATA_H                (15),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (17),
		.OUT_PKT_BYTEEN_L              (16),
		.OUT_PKT_BYTE_CNT_H            (58),
		.OUT_PKT_BYTE_CNT_L            (56),
		.OUT_PKT_TRANS_COMPRESSED_READ (50),
		.OUT_PKT_BURST_SIZE_H          (62),
		.OUT_PKT_BURST_SIZE_L          (60),
		.OUT_PKT_RESPONSE_STATUS_H     (80),
		.OUT_PKT_RESPONSE_STATUS_L     (79),
		.OUT_PKT_TRANS_EXCLUSIVE       (55),
		.OUT_PKT_BURST_TYPE_H          (64),
		.OUT_PKT_BURST_TYPE_L          (63),
		.OUT_ST_DATA_W                 (81),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0)
	) width_adapter (
		.clk                  (clk_clk),                           //       clk.clk
		.reset                (rst_controller_reset_out_reset),    // clk_reset.reset
		.in_valid             (cmd_xbar_demux_src0_valid),         //      sink.valid
		.in_channel           (cmd_xbar_demux_src0_channel),       //          .channel
		.in_startofpacket     (cmd_xbar_demux_src0_startofpacket), //          .startofpacket
		.in_endofpacket       (cmd_xbar_demux_src0_endofpacket),   //          .endofpacket
		.in_ready             (cmd_xbar_demux_src0_ready),         //          .ready
		.in_data              (cmd_xbar_demux_src0_data),          //          .data
		.out_endofpacket      (width_adapter_src_endofpacket),     //       src.endofpacket
		.out_data             (width_adapter_src_data),            //          .data
		.out_channel          (width_adapter_src_channel),         //          .channel
		.out_valid            (width_adapter_src_valid),           //          .valid
		.out_ready            (width_adapter_src_ready),           //          .ready
		.out_startofpacket    (width_adapter_src_startofpacket),   //          .startofpacket
		.in_command_size_data (3'b000)                             // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (49),
		.IN_PKT_ADDR_L                 (18),
		.IN_PKT_DATA_H                 (15),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (17),
		.IN_PKT_BYTEEN_L               (16),
		.IN_PKT_BYTE_CNT_H             (58),
		.IN_PKT_BYTE_CNT_L             (56),
		.IN_PKT_TRANS_COMPRESSED_READ  (50),
		.IN_PKT_BURSTWRAP_H            (59),
		.IN_PKT_BURSTWRAP_L            (59),
		.IN_PKT_BURST_SIZE_H           (62),
		.IN_PKT_BURST_SIZE_L           (60),
		.IN_PKT_RESPONSE_STATUS_H      (80),
		.IN_PKT_RESPONSE_STATUS_L      (79),
		.IN_PKT_TRANS_EXCLUSIVE        (55),
		.IN_PKT_BURST_TYPE_H           (64),
		.IN_PKT_BURST_TYPE_L           (63),
		.IN_ST_DATA_W                  (81),
		.OUT_PKT_ADDR_H                (67),
		.OUT_PKT_ADDR_L                (36),
		.OUT_PKT_DATA_H                (31),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (35),
		.OUT_PKT_BYTEEN_L              (32),
		.OUT_PKT_BYTE_CNT_H            (76),
		.OUT_PKT_BYTE_CNT_L            (74),
		.OUT_PKT_TRANS_COMPRESSED_READ (68),
		.OUT_PKT_BURST_SIZE_H          (80),
		.OUT_PKT_BURST_SIZE_L          (78),
		.OUT_PKT_RESPONSE_STATUS_H     (98),
		.OUT_PKT_RESPONSE_STATUS_L     (97),
		.OUT_PKT_TRANS_EXCLUSIVE       (73),
		.OUT_PKT_BURST_TYPE_H          (82),
		.OUT_PKT_BURST_TYPE_L          (81),
		.OUT_ST_DATA_W                 (99),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (1),
		.RESPONSE_PATH                 (1)
	) width_adapter_001 (
		.clk                  (clk_clk),                             //       clk.clk
		.reset                (rst_controller_reset_out_reset),      // clk_reset.reset
		.in_valid             (id_router_src_valid),                 //      sink.valid
		.in_channel           (id_router_src_channel),               //          .channel
		.in_startofpacket     (id_router_src_startofpacket),         //          .startofpacket
		.in_endofpacket       (id_router_src_endofpacket),           //          .endofpacket
		.in_ready             (id_router_src_ready),                 //          .ready
		.in_data              (id_router_src_data),                  //          .data
		.out_endofpacket      (width_adapter_001_src_endofpacket),   //       src.endofpacket
		.out_data             (width_adapter_001_src_data),          //          .data
		.out_channel          (width_adapter_001_src_channel),       //          .channel
		.out_valid            (width_adapter_001_src_valid),         //          .valid
		.out_ready            (width_adapter_001_src_ready),         //          .ready
		.out_startofpacket    (width_adapter_001_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                               // (terminated)
	);

endmodule
