# TCL File Generated by Component Editor 13.0sp1
# Sun Dec 03 21:25:37 IST 2017
# DO NOT MODIFY


# 
# BCD "BCD Avalon" v1.0
# Doron Kopit 2017.12.03.21:25:37
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module BCD
# 
set_module_property DESCRIPTION ""
set_module_property NAME BCD
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Doron Kopit"
set_module_property DISPLAY_NAME "BCD Avalon"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL BCD_Avalon_Top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file BCD_Avalon_Top.vhd VHDL PATH ../hdl/BCD_Avalon_Top.vhd TOP_LEVEL_FILE
add_fileset_file BCD_digit.vhd VHDL PATH ../hdl/BCD_digit.vhd
add_fileset_file BCD_top.vhd VHDL PATH ../hdl/BCD_top.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avmm
# 
add_interface avmm avalon end
set_interface_property avmm addressUnits WORDS
set_interface_property avmm associatedClock clock
set_interface_property avmm associatedReset reset
set_interface_property avmm bitsPerSymbol 8
set_interface_property avmm burstOnBurstBoundariesOnly false
set_interface_property avmm burstcountUnits WORDS
set_interface_property avmm explicitAddressSpan 0
set_interface_property avmm holdTime 0
set_interface_property avmm linewrapBursts false
set_interface_property avmm maximumPendingReadTransactions 0
set_interface_property avmm readLatency 1
set_interface_property avmm readWaitTime 1
set_interface_property avmm setupTime 0
set_interface_property avmm timingUnits Cycles
set_interface_property avmm writeWaitTime 0
set_interface_property avmm ENABLED true
set_interface_property avmm EXPORT_OF ""
set_interface_property avmm PORT_NAME_MAP ""
set_interface_property avmm SVD_ADDRESS_GROUP ""

add_interface_port avmm avmm_address address Input 3
add_interface_port avmm avmm_waitrequest waitrequest Output 1
add_interface_port avmm avmm_read read Input 1
add_interface_port avmm avmm_readdata readdata Output 32
add_interface_port avmm avmm_write write Input 1
add_interface_port avmm avmm_writedata writedata Input 32
add_interface_port avmm avmm_byteenable byteenable Input 4
set_interface_assignment avmm embeddedsw.configuration.isFlash 0
set_interface_assignment avmm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avmm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avmm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point IO
# 
add_interface IO conduit end
set_interface_property IO associatedClock clock
set_interface_property IO associatedReset reset
set_interface_property IO ENABLED true
set_interface_property IO EXPORT_OF ""
set_interface_property IO PORT_NAME_MAP ""
set_interface_property IO SVD_ADDRESS_GROUP ""

add_interface_port IO bcd_pinout bcd_pinout Output 8
add_interface_port IO error error Output 1
add_interface_port IO enable_pinout bcd_en_pinout Output 8


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rstn reset_n Input 1

